apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-other
  labels:
    app: cloud-other
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-other
  template:
    metadata:
      labels:
        app: cloud-other
    spec:
      containers:
        - name: my-java-app
          image: cloud-other:1.0
          ports:
            - containerPort: 8686